// Code generated by mockery v2.39.2. DO NOT EDIT.

package mocks

import (
	book "library_api/features/book"

	jwt "github.com/golang-jwt/jwt/v5"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddBook provides a mock function with given fields: token, newBook
func (_m *Service) AddBook(token *jwt.Token, newBook book.Book) (book.Book, error) {
	ret := _m.Called(token, newBook)

	if len(ret) == 0 {
		panic("no return value specified for AddBook")
	}

	var r0 book.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, book.Book) (book.Book, error)); ok {
		return rf(token, newBook)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token, book.Book) book.Book); ok {
		r0 = rf(token, newBook)
	} else {
		r0 = ret.Get(0).(book.Book)
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token, book.Book) error); ok {
		r1 = rf(token, newBook)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DelBook provides a mock function with given fields: token, bookID
func (_m *Service) DelBook(token *jwt.Token, bookID uint) error {
	ret := _m.Called(token, bookID)

	if len(ret) == 0 {
		panic("no return value specified for DelBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, uint) error); ok {
		r0 = rf(token, bookID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBook provides a mock function with given fields: bookID
func (_m *Service) GetBook(bookID uint) (book.Book, error) {
	ret := _m.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetBook")
	}

	var r0 book.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (book.Book, error)); ok {
		return rf(bookID)
	}
	if rf, ok := ret.Get(0).(func(uint) book.Book); ok {
		r0 = rf(bookID)
	} else {
		r0 = ret.Get(0).(book.Book)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(bookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchBook provides a mock function with given fields: tittle, page, limit
func (_m *Service) SearchBook(tittle string, page uint, limit uint) ([]book.Book, uint, error) {
	ret := _m.Called(tittle, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchBook")
	}

	var r0 []book.Book
	var r1 uint
	var r2 error
	if rf, ok := ret.Get(0).(func(string, uint, uint) ([]book.Book, uint, error)); ok {
		return rf(tittle, page, limit)
	}
	if rf, ok := ret.Get(0).(func(string, uint, uint) []book.Book); ok {
		r0 = rf(tittle, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(string, uint, uint) uint); ok {
		r1 = rf(tittle, page, limit)
	} else {
		r1 = ret.Get(1).(uint)
	}

	if rf, ok := ret.Get(2).(func(string, uint, uint) error); ok {
		r2 = rf(tittle, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateBook provides a mock function with given fields: token, bookID, input
func (_m *Service) UpdateBook(token *jwt.Token, bookID uint, input book.Book) (book.Book, error) {
	ret := _m.Called(token, bookID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 book.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, uint, book.Book) (book.Book, error)); ok {
		return rf(token, bookID, input)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token, uint, book.Book) book.Book); ok {
		r0 = rf(token, bookID, input)
	} else {
		r0 = ret.Get(0).(book.Book)
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token, uint, book.Book) error); ok {
		r1 = rf(token, bookID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
